services:
  fe:
    build:
      context: ./FE
    container_name: compassed-fe
    restart: unless-stopped
    environment:
      FE_HOST: 0.0.0.0
      FE_PORT: 3000
      API_BASE: https://compassed.io.vn
      GOOGLE_CLIENT_ID: "759011701592-v4npda3hrmcrsh8s8cnq2jh5jcuc755o.apps.googleusercontent.com"
    ports:
      - "3000:3000"

  be:
    build:
      context: ./BE/compassed-api
    container_name: compassed-be
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      MYSQL_URL: jdbc:mysql://mysql:3306/compassed?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      JWT_SECRET: this-is-a-very-strong-jwt-secret-min-32
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    container_name: compassed-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: compassed
    ports:
      - "3307:3306"
    volumes:
      - compassed_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-uroot", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  compassed_mysql_data:
