services:
  fe:
    build:
      context: ./FE
    container_name: compassed-fe
    restart: unless-stopped
    environment:
      FE_HOST: 0.0.0.0
      FE_PORT: 3000
      API_BASE: https://compassed.io.vn
      GOOGLE_CLIENT_ID: 418581116582-qet8ant9k0t319hkd3640dtsa54eg07v.apps.googleusercontent.com
    ports:
      - "3000:3000"

  be:
    build:
      context: ./BE/compassed-api
    container_name: compassed-be
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      GOOGLE_CLIENT_ID: 418581116582-qet8ant9k0t319hkd3640dtsa54eg07v.apps.googleusercontent.com
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: fonght.dev@gmail.com
      MAIL_PASSWORD: yylmvpdohcxcvhzl
      MAIL_FROM: fonght.dev@gmail.com
      MYSQL_URL: jdbc:mysql://mysql:3306/compassed?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      JWT_SECRET: this-is-a-very-strong-jwt-secret-min-32
      SERVER_PORT: 8080
      CHECKOUT_QR_IMAGE_URL: https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=CompassED_Payment_Placeholder
      CHECKOUT_QR_ACCOUNT_NAME: COMPASSED
      CHECKOUT_QR_ACCOUNT_NO: 8990186866886
      CHECKOUT_QR_BANK: VietQR
      CHECKOUT_QR_BANK_BIN: 970422
      PAYOS_ENABLED: "true"
      PAYOS_CLIENT_ID: "64cb95c4-4a51-4ea7-b706-80ad9431d07c"
      PAYOS_API_KEY: "1db41152-008c-4b99-9c13-31cb5945e338"
      PAYOS_CHECKSUM_KEY: "cd111aebc37699c0b0223595fde809ec7752d8354f1e11b406ffba893b28fdcd"
      PAYOS_BASE_URL: https://api-merchant.payos.vn
      PAYOS_RETURN_URL: https://compassed.io.vn/checkout
      PAYOS_CANCEL_URL: https://compassed.io.vn/checkout
      PAYOS_CHECK_COOLDOWN_SECONDS: 15
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    container_name: compassed-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: compassed
    ports:
      - "3307:3306"
    volumes:
      - compassed_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-uroot", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  compassed_mysql_data:
