ALTER TABLE users
    ADD COLUMN IF NOT EXISTS created_at DATETIME NULL;

UPDATE users
SET created_at = NOW()
WHERE created_at IS NULL;

ALTER TABLE users
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
